export { ReactComponent as AppleIcon } from './apple.svg';
export { ReactComponent as LinuxIcon } from './linux.svg';
export { ReactComponent as WindowsIcon } from './windows.svg';
export { ReactComponent as HeartIcon } from './heart.svg';
export { ReactComponent as YouTubeIcon } from './youtube.svg';
export { ReactComponent as TwitterIcon } from './twitter.svg';
export { ReactComponent as FacebookIcon } from './facebook.svg';
export { ReactComponent as AddToCartIcon } from './add-to-cart.svg';
export { ReactComponent as WebIcon } from './web.svg';
