{{- $deployment := .Values.backend -}}
{{- $deploymentName := printf "%s-%s" .Release.Name $deployment.name }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    app: {{ .Chart.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    role: {{ $deployment.role }}
  annotations:
    released: {{ .Release.Time}}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      role: {{ $deployment.role }}
  replicas: {{ $deployment.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        role: {{ $deployment.role }}
      annotations:
        released: {{ .Release.Time}}
    spec:
      serviceAccountName: {{ .Release.Name }}
      containers:
        - name: {{ $deployment.name }}
          image: {{ $deployment.image }}:{{ $deployment.imageTag }}
          ports:
            {{- range $port := $deployment.ports }}
            - containerPort: {{ $port.port }}
            {{- end }}
          env:
            - name: REACT_APP_API_URL
              value: "https://store.tst.qilin.super.com/api"
            - name: REACT_APP_QILIN_SDK_INIT_URL
              value: "sdk/v1"
          #livenessProbe:
          #  httpGet:
          #    path: /health
          #    port: {{ $deployment.healthPort }}
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          #  failureThreshold: 3
          #  periodSeconds: 5
          #volumeMounts:
          #- name: {{ $deploymentName }}-config
          #  mountPath: /application/etc/
          #  readOnly: tru
