export const CHECK_FOR_UPDATE_PENDING = 'CHECK_FOR_UPDATE_PENDING';
export const CHECK_FOR_UPDATE_SUCCESS = 'CHECK_FOR_UPDATE_SUCCESS';
export const CHECK_FOR_UPDATE_FAILURE = 'CHECK_FOR_UPDATE_FAILURE';

export const UPDATE_AVAILABLE = 'UPDATE_AVAILABLE';
export const UPDATE_NOT_AVAILABLE = 'UPDATE_NOT_AVAILABLE';

export const DOWNLOAD_UPDATE_PENDING = 'DOWNLOAD_UPDATE_PENDING';
export const DOWNLOAD_UPDATE_SUCCESS = 'DOWNLOAD_UPDATE_SUCCESS';
export const DOWNLOAD_UPDATE_FAILURE = 'DOWNLOAD_UPDATE_FAILURE';
export const DOWNLOAD_PROGRESS = 'DOWNLOAD_PROGRESS';

export const QUIT_AND_INSTALL_UPDATE = 'QUIT_AND_INSTALL_UPDATE';

export const APP_INIT = 'APP_INIT';

export const AUTH_GUEST = 'AUTH_GUEST';

export const OPEN_LINK = 'OPEN_LINK';
