version: '3.7'
services:
  crm-dashboard:
    container_name: qilin-store-ui
    image: p1hub/qilin-store-ui:${TAG}
    restart: on-failure
    networks:
      - default
networks:
  default:
    name: ${DOCKER_NETWORK}
    external: true
